{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.monitoring.serviceMonitor.labels }}
    {{ toYaml .Values.monitoring.serviceMonitor.labels }}
    {{- end }}    
  name: {{ template "pihole.fullname" . }}-prometheus-exporter
{{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
{{- end }}
spec:
  endpoints:
  - targetPort: {{ .Values.monitoring.port }}
    path: /metrics
{{- if .Values.monitoring.serviceMonitor.interval }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
{{- if .Values.monitoring.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ .Values.monitoring.serviceMonitor.bearerTokenFile }}
{{- end }}
{{- if .Values.monitoring.serviceMonitor.bearerTokenSecret }}
    bearerTokenSecret:
      name: {{ .Values.monitoring.serviceMonitor.bearerTokenSecret.name }}
      key: {{ .Values.monitoring.serviceMonitor.bearerTokenSecret.key }}
      {{- if .Values.monitoring.serviceMonitor.bearerTokenSecret.optional }}
      optional: {{ .Values.monitoring.serviceMonitor.bearerTokenSecret.optional }}
      {{- end }}
{{- end }}
  jobLabel: {{ template "pihole.fullname" . }}-prometheus-exporter
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "pihole.name" . }}
      release: {{ .Release.Name }}
{{- end }}
